/* ASN.1 System configuration file for function sender
 * Generated by TASTE on 2021-11-24 12:45:20
 */
#define __NEED_MyInteger_NATIVE
#define __NEED_MyInteger_NATIVE
#define __NEED_MyInteger_NATIVE
#define __NEED_RawData_NATIVE
