/* Body file for function sender
 * Generated by TASTE on 2021-07-02 18:36:53
 * You can edit this file, it will not be overwritten
 * Provided interfaces : trigger
 * Required interfaces : image
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 91662 76325 121615 120171
 * Timers              : 
 */

#include "sender.h"
//#include "raw.h"
#include <stdio.h>


void sender_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   puts ("[sender] Startup");
}

void sender_PI_trigger(void)
{
    asn1SccRawData raw_data;
    int i;
    for (i=0; i<12582912; i++){
        raw_data.arr[i]=0x2;
    }
    puts ("Sending image");
   sender_RI_image( &raw_data );
}


void sender_PI_testint( const asn1SccMyInteger *IN_int2 ){
    if (*IN_int2 ==0 )
        puts("[Receiver] Correct Data");
    else
        printf("WRONG VALUES: %d", *IN_int2);
    
}
