/* Body file for function sender
 * Generated by TASTE on 2021-11-24 15:50:50
 * Provided interfaces : b, d, f, h, j, l, n, p, r, t, testint, trigger, v, x, z
 * Required interfaces : a, c, e, g, i, image, k, m, o, q, s, u, w, y
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 73619 3500 114759 183955
 * Timers              : 
 */
#include "sender_vm_if.h"
#include "C_ASN1_Types.h"
#ifdef __unix__
   #include <stdio.h>
#endif




extern void init_receiver(void);
extern unsigned receiver_initialized;
extern void init_receiver(void);
extern unsigned receiver_initialized;
extern void init_receiver(void);
extern unsigned receiver_initialized;
extern void init_receiver(void);
extern unsigned receiver_initialized;
extern void init_receiver(void);
extern unsigned receiver_initialized;
extern void init_receiver(void);
extern unsigned receiver_initialized;
extern void init_receiver(void);
extern unsigned receiver_initialized;
extern void init_receiver(void);
extern unsigned receiver_initialized;
extern void init_receiver(void);
extern unsigned receiver_initialized;
extern void init_receiver(void);
extern unsigned receiver_initialized;
extern void init_receiver(void);
extern unsigned receiver_initialized;
extern void init_receiver(void);
extern unsigned receiver_initialized;
unsigned sender_initialized = 0;
void init_sender(void)
{
   if (0 == sender_initialized) {
      sender_initialized = 1;
      // Call user code startup function
      extern void sender_startup(void);
      sender_startup();
      // Iterate over all synchronous RIs, and call their parent's
      // init function. Multiple calls are prevented by the "init" guard.
      if (0 == receiver_initialized) {
          init_receiver();
      }
      if (0 == receiver_initialized) {
          init_receiver();
      }
      if (0 == receiver_initialized) {
          init_receiver();
      }
      if (0 == receiver_initialized) {
          init_receiver();
      }
      if (0 == receiver_initialized) {
          init_receiver();
      }
      if (0 == receiver_initialized) {
          init_receiver();
      }
      if (0 == receiver_initialized) {
          init_receiver();
      }
      if (0 == receiver_initialized) {
          init_receiver();
      }
      if (0 == receiver_initialized) {
          init_receiver();
      }
      if (0 == receiver_initialized) {
          init_receiver();
      }
      if (0 == receiver_initialized) {
          init_receiver();
      }
      if (0 == receiver_initialized) {
          init_receiver();
      }
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function sender");
#endif
      sender_initialized = 2;
   }
}
void sender_b
      (const char *IN_varb, size_t IN_varb_len)

{
#ifdef __unix__
   // Log MSC data on Linux when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
      innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: sender,b,%lld\n", msc_time);
      fflush(stdout);
  }
#endif

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void sender_PI_b
      (const asn1SccMyInteger *);




   // Call user code
   sender_PI_b ((asn1SccMyInteger *)IN_varb);

}
void sender_d
      (const char *IN_vard, size_t IN_vard_len)

{
#ifdef __unix__
   // Log MSC data on Linux when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
      innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: sender,d,%lld\n", msc_time);
      fflush(stdout);
  }
#endif

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void sender_PI_d
      (const asn1SccMyInteger *);




   // Call user code
   sender_PI_d ((asn1SccMyInteger *)IN_vard);

}
void sender_f
      (const char *IN_varf, size_t IN_varf_len)

{
#ifdef __unix__
   // Log MSC data on Linux when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
      innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: sender,f,%lld\n", msc_time);
      fflush(stdout);
  }
#endif

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void sender_PI_f
      (const asn1SccMyInteger *);




   // Call user code
   sender_PI_f ((asn1SccMyInteger *)IN_varf);

}
void sender_h
      (const char *IN_varh, size_t IN_varh_len)

{
#ifdef __unix__
   // Log MSC data on Linux when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
      innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: sender,h,%lld\n", msc_time);
      fflush(stdout);
  }
#endif

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void sender_PI_h
      (const asn1SccMyInteger *);




   // Call user code
   sender_PI_h ((asn1SccMyInteger *)IN_varh);

}
void sender_j
      (const char *IN_j, size_t IN_j_len)

{
#ifdef __unix__
   // Log MSC data on Linux when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
      innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: sender,j,%lld\n", msc_time);
      fflush(stdout);
  }
#endif

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void sender_PI_j
      (const asn1SccMyInteger *);




   // Call user code
   sender_PI_j ((asn1SccMyInteger *)IN_j);

}
void sender_l
      (const char *IN_varl, size_t IN_varl_len)

{
#ifdef __unix__
   // Log MSC data on Linux when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
      innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: sender,l,%lld\n", msc_time);
      fflush(stdout);
  }
#endif

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void sender_PI_l
      (const asn1SccMyInteger *);




   // Call user code
   sender_PI_l ((asn1SccMyInteger *)IN_varl);

}
void sender_n
      (const char *IN_varn, size_t IN_varn_len)

{
#ifdef __unix__
   // Log MSC data on Linux when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
      innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: sender,n,%lld\n", msc_time);
      fflush(stdout);
  }
#endif

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void sender_PI_n
      (const asn1SccMyInteger *);




   // Call user code
   sender_PI_n ((asn1SccMyInteger *)IN_varn);

}
void sender_p
      (const char *IN_varp, size_t IN_varp_len)

{
#ifdef __unix__
   // Log MSC data on Linux when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
      innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: sender,p,%lld\n", msc_time);
      fflush(stdout);
  }
#endif

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void sender_PI_p
      (const asn1SccMyInteger *);




   // Call user code
   sender_PI_p ((asn1SccMyInteger *)IN_varp);

}
void sender_r
      (const char *IN_varr, size_t IN_varr_len)

{
#ifdef __unix__
   // Log MSC data on Linux when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
      innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: sender,r,%lld\n", msc_time);
      fflush(stdout);
  }
#endif

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void sender_PI_r
      (const asn1SccMyInteger *);




   // Call user code
   sender_PI_r ((asn1SccMyInteger *)IN_varr);

}
void sender_t
      (const char *IN_vart, size_t IN_vart_len)

{
#ifdef __unix__
   // Log MSC data on Linux when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
      innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: sender,t,%lld\n", msc_time);
      fflush(stdout);
  }
#endif

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void sender_PI_t
      (const asn1SccMyInteger *);




   // Call user code
   sender_PI_t ((asn1SccMyInteger *)IN_vart);

}
void sender_testint
      (const char *IN_int2, size_t IN_int2_len)

{
#ifdef __unix__
   // Log MSC data on Linux when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
      innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: sender,testint,%lld\n", msc_time);
      fflush(stdout);
  }
#endif

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void sender_PI_testint
      (const asn1SccMyInteger *);




   // Call user code
   sender_PI_testint ((asn1SccMyInteger *)IN_int2);

}
void sender_trigger()
{
#ifdef __unix__
   // Log MSC data on Linux when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
      innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: sender,trigger,%lld\n", msc_time);
      fflush(stdout);
  }
#endif

   //  Directly call user code, no parameters to pass
   extern void sender_PI_trigger(void);
   sender_PI_trigger();
   // puts ("sender_trigger called");
}
void sender_v
      (const char *IN_varv, size_t IN_varv_len)

{
#ifdef __unix__
   // Log MSC data on Linux when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
      innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: sender,v,%lld\n", msc_time);
      fflush(stdout);
  }
#endif

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void sender_PI_v
      (const asn1SccMyInteger *);




   // Call user code
   sender_PI_v ((asn1SccMyInteger *)IN_varv);

}
void sender_x
      (const char *IN_varx, size_t IN_varx_len)

{
#ifdef __unix__
   // Log MSC data on Linux when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
      innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: sender,x,%lld\n", msc_time);
      fflush(stdout);
  }
#endif

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void sender_PI_x
      (const asn1SccMyInteger *);




   // Call user code
   sender_PI_x ((asn1SccMyInteger *)IN_varx);

}
void sender_z
      (const char *IN_varz, size_t IN_varz_len)

{
#ifdef __unix__
   // Log MSC data on Linux when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
      innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: sender,z,%lld\n", msc_time);
      fflush(stdout);
  }
#endif

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void sender_PI_z
      (const asn1SccMyInteger *);




   // Call user code
   sender_PI_z ((asn1SccMyInteger *)IN_varz);

}

