/* Body file for function receiver
 * Generated by TASTE on 2021-07-02 18:36:53
 * You can edit this file, it will not be overwritten
 * Provided interfaces : image
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 173581 76867 209488 121074
 * Timers              : 
 */

#include "receiver.h"
//#include <stdio.h>


void receiver_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // puts ("[receiver] Startup");
}

void receiver_PI_image
      (const asn1SccRawData *IN_img_data)

{
   puts("[Receiver] Got image!");
}


