/* Body file for function receiver
 * Generated by TASTE on 2021-07-02 18:36:53
 * You can edit this file, it will not be overwritten
 * Provided interfaces : image
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 173581 76867 209488 121074
 * Timers              : 
 */

#include "receiver.h"
#include <stdio.h>


void receiver_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // puts ("[receiver] Startup");
}

void receiver_PI_image
      (const asn1SccRawData *IN_img_data)

{
    asn1SccMyInteger i, result=0;
   puts("[Receiver] Got image!");
   for (i=0; i<4194304; i++){
       if(IN_img_data->arr[i] != 0x2)
           result ++;
   }

    receiver_RI_testint( &result );
}


void receiver_PI_a( const asn1SccMyInteger *IN_vara ){
    receiver_RI_b( IN_vara);
}

void receiver_PI_c( const asn1SccMyInteger *IN_varc ){
    receiver_RI_d( IN_varc );
}

void receiver_PI_e( const asn1SccMyInteger *IN_vare ){
    receiver_RI_f( IN_vare);
}

void receiver_PI_g( const asn1SccMyInteger *IN_varg ){
    receiver_RI_h( IN_varg );
}

void receiver_PI_i( const asn1SccMyInteger *IN_vari ){
    receiver_RI_j( IN_vari);
}

void receiver_PI_k( const asn1SccMyInteger *IN_vark ){
    receiver_RI_l( IN_vark);
}




void receiver_PI_m( const asn1SccMyInteger *IN_varm ){
    receiver_RI_n( IN_varm);
}

void receiver_PI_o( const asn1SccMyInteger *IN_varo ){
    receiver_RI_p( IN_varo );
}

void receiver_PI_q( const asn1SccMyInteger *IN_varq ){
    receiver_RI_r( IN_varq);
}

void receiver_PI_s( const asn1SccMyInteger *IN_vars ){
    receiver_RI_t( IN_vars );
}

void receiver_PI_u( const asn1SccMyInteger *IN_varu ){
    receiver_RI_v( IN_varu);
}

void receiver_PI_w( const asn1SccMyInteger *IN_varw ){
    receiver_RI_x( IN_varw);
}

void receiver_PI_y( const asn1SccMyInteger *IN_vary ){
    receiver_RI_z( IN_vary);
}


