/* Body file for function receiver
 * Generated by TASTE on 2021-07-02 18:36:53
 * You can edit this file, it will not be overwritten
 * Provided interfaces : image
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 173581 76867 209488 121074
 * Timers              : 
 */

#include "receiver.h"
#include <stdio.h>


void receiver_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // puts ("[receiver] Startup");
}

void receiver_PI_image
      (const asn1SccRawData *IN_img_data)

{
    asn1SccMyInteger i, result=0;
   puts("[Receiver] Got image!");
   for (i=0; i<4194304; i++){
       if(IN_img_data->arr[i] != 0x2)
           result ++;
   }

    receiver_RI_testint( &result );
}


void receiver_PI_a( const asn1SccMyInteger *IN_vara ){
    receiver_RI_b( IN_vara);
}

void receiver_PI_c( const asn1SccMyInteger *IN_varc ){
    receiver_RI_d( IN_varc );
}

void receiver_PI_e( const asn1SccMyInteger *IN_vare ){
}


