
/* Header file for function sender in C language
 * Generated by TASTE on 2021-11-24 15:50:50
 * Context Parameters present : NO
 * Provided interfaces : b, d, f, h, j, l, n, p, r, t, testint, trigger, v, x, z
 * Required interfaces : a, c, e, g, i, image, k, m, o, q, s, u, w, y
 * User-defined properties for this function:
  *  |_ Taste::Active_Interfaces = any
  *  |_ Taste::coordinates = 73619 3500 114759 183955
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void sender_startup(void);

/* Provided interfaces */
void sender_PI_b( const asn1SccMyInteger * );
void sender_PI_d( const asn1SccMyInteger * );
void sender_PI_f( const asn1SccMyInteger * );
void sender_PI_h( const asn1SccMyInteger * );
void sender_PI_j( const asn1SccMyInteger * );
void sender_PI_l( const asn1SccMyInteger * );
void sender_PI_n( const asn1SccMyInteger * );
void sender_PI_p( const asn1SccMyInteger * );
void sender_PI_r( const asn1SccMyInteger * );
void sender_PI_t( const asn1SccMyInteger * );
void sender_PI_testint( const asn1SccMyInteger * );
void sender_PI_trigger( void );
void sender_PI_v( const asn1SccMyInteger * );
void sender_PI_x( const asn1SccMyInteger * );
void sender_PI_z( const asn1SccMyInteger * );

/* Required interfaces */
extern void sender_RI_a( const asn1SccMyInteger * );
extern void sender_RI_c( const asn1SccMyInteger * );
extern void sender_RI_e( const asn1SccMyInteger * );
extern void sender_RI_g( const asn1SccMyInteger * );
extern void sender_RI_i( const asn1SccMyInteger * );
extern void sender_RI_image( const asn1SccRawData * );
extern void sender_RI_k( const asn1SccMyInteger * );
extern void sender_RI_m( const asn1SccMyInteger * );
extern void sender_RI_o( const asn1SccMyInteger * );
extern void sender_RI_q( const asn1SccMyInteger * );
extern void sender_RI_s( const asn1SccMyInteger * );
extern void sender_RI_u( const asn1SccMyInteger * );
extern void sender_RI_w( const asn1SccMyInteger * );
extern void sender_RI_y( const asn1SccMyInteger * );


#ifdef __cplusplus
}
#endif
