/* Body file for function receiver
 * Generated by TASTE on 2021-07-29 10:20:34
 * Provided interfaces : image
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 159687 72536 216344 101045
 * Timers              : 
 */
#include "receiver_vm_if.h"
#include "C_ASN1_Types.h"
#ifdef __unix__
   #include <stdio.h>
#endif




unsigned receiver_initialized = 0;
void init_receiver(void)
{
   if (0 == receiver_initialized) {
      receiver_initialized = 1;
      // Call user code startup function
      extern void receiver_startup(void);
      receiver_startup();
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function receiver");
#endif
      receiver_initialized = 2;
   }
}
void receiver_image
      (const char *IN_img_data, size_t IN_img_data_len)

{

   static asn1SccRawData IN_IMG_DATA;
#ifdef __unix__
   asn1SccRawData_Initialize(&IN_IMG_DATA);
#endif
   if (0 != Decode_NATIVE_RawData (&IN_IMG_DATA, (void *)IN_img_data, IN_img_data_len)) {
      #ifdef __unix__
         puts("Error decoding RawData in function receiver_image");
      #endif
      return;
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void receiver_PI_image
      (const asn1SccRawData *);




   // Call user code
   receiver_PI_image (&IN_IMG_DATA);

}

