/* Body file for function sender
 * Generated by TASTE on 2021-08-04 10:55:18
 * Provided interfaces : testint, trigger
 * Required interfaces : image
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 89677 72716 130817 101406
 * Timers              : 
 */
#include "sender_vm_if.h"
#include "C_ASN1_Types.h"
#ifdef __unix__
   #include <stdio.h>
#endif




unsigned sender_initialized = 0;
void init_sender(void)
{
   if (0 == sender_initialized) {
      sender_initialized = 1;
      // Call user code startup function
      extern void sender_startup(void);
      sender_startup();
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function sender");
#endif
      sender_initialized = 2;
   }
}
void sender_testint
      (const char *IN_int2, size_t IN_int2_len)

{

   static asn1SccMyInteger IN_INT2;
#ifdef __unix__
   asn1SccMyInteger_Initialize(&IN_INT2);
#endif
   if (0 != Decode_NATIVE_MyInteger (&IN_INT2, (void *)IN_int2, IN_int2_len)) {
      #ifdef __unix__
         puts("Error decoding MyInteger in function sender_testint");
      #endif
      return;
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void sender_PI_testint
      (const asn1SccMyInteger *);




   // Call user code
   sender_PI_testint (&IN_INT2);

}
void sender_trigger()
{
   //  Directly call user code, no parameters to pass
   extern void sender_PI_trigger(void);
   sender_PI_trigger();
   // puts ("sender_trigger called");
}

