/* Body file for function receiver
 * Generated by TASTE on 2021-10-26 16:34:28
 * Provided interfaces : image
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 159687 72536 216344 101045
 * Timers              : 
 */
#include "receiver_vm_if.h"
#include "C_ASN1_Types.h"
#ifdef __unix__
   #include <stdio.h>
#endif




unsigned receiver_initialized = 0;
void init_receiver(void)
{
   if (0 == receiver_initialized) {
      receiver_initialized = 1;
      // Call user code startup function
      extern void receiver_startup(void);
      receiver_startup();
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function receiver");
#endif
      receiver_initialized = 2;
   }
}
void receiver_image
      (const char *IN_img_data, size_t IN_img_data_len)

{
#ifdef __unix__
   // Log MSC data on Linux when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
      innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: receiver,image,%lld\n", msc_time);
      fflush(stdout);
  }
#endif

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void receiver_PI_image
      (const asn1SccRawData *);




   // Call user code
   receiver_PI_image ((asn1SccRawData *)IN_img_data);

}

