
/* Header file for function receiver in C language
 * Generated by TASTE on 2021-11-24 12:46:05
 * Context Parameters present : NO
 * Provided interfaces : a, c, image
 * Required interfaces : b, d, testint
 * User-defined properties for this function:
  *  |_ Taste::Active_Interfaces = any
  *  |_ Taste::coordinates = 159687 72536 216344 141824
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void receiver_startup(void);

/* Provided interfaces */
void receiver_PI_a( const asn1SccMyInteger * );
void receiver_PI_c( const asn1SccMyInteger * );
void receiver_PI_image( const asn1SccRawData * );

/* Required interfaces */
extern void receiver_RI_b( const asn1SccMyInteger * );
extern void receiver_RI_d( const asn1SccMyInteger * );
extern void receiver_RI_testint( const asn1SccMyInteger * );


#ifdef __cplusplus
}
#endif
